import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { NoteStore } from '../shared/store.mjs';
import { connectionInfo } from '../shared/connections.mjs';

test('stdio MCP creates notes and inputs visible to the app storage, and protects concurrent edits', async t => {
  const dir = await fs.mkdtemp(path.join(tmpdir(), 'margin-mcp-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const client = new Client({ name: 'test-codex', version: '1.0.0' });
  const transport = new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../server/index.mjs', import.meta.url))], env: { ...process.env, MARGIN_DATA_DIR: dir }, stderr: 'pipe' });
  await client.connect(transport); t.after(() => client.close());
  const tools = await client.listTools(); assert.equal(tools.tools.length, 17);
  assert.ok(tools.tools.find(t => t.name === 'list_notes').annotations.readOnlyHint);
  const call = async (name, args) => { const result = await client.callTool({ name, arguments: args }); assert.ok(!result.isError, result.content?.[0]?.text); return JSON.parse(result.content[0].text); };
  const folder = await call('create_folder', { name: 'Agent workspace', color: 'sage' });
  const note = await call('create_note', { title: 'Conversation decisions', body: 'We chose local storage.', folderId: folder.id, source: 'Codex' });
  await call('add_input', { id: note.id, type: 'task', text: 'Review the beta', source: 'Claude' });
  await call('add_input', { id: note.id, type: 'link', text: 'MCP docs', url: 'https://modelcontextprotocol.io', source: 'Codex' });
  await call('add_input', { id: note.id, type: 'code', text: 'const a = `literal`;', language: 'js', source: 'Codex' });
  const store = await new NoteStore(dir).init(); const saved = await store.get(note.id);
  assert.match(saved.body, /- \[ \] Review the beta/); assert.match(saved.body, /\[MCP docs\]/); assert.match(saved.body, /```js\nconst a/);
  const stale = await client.callTool({ name: 'update_note', arguments: { id: note.id, body: 'overwrite', expectedRevision: note.revision } });
  assert.equal(stale.isError, true); assert.match(stale.content[0].text, /changed in another app/);
  assert.equal((await store.get(note.id)).body, saved.body);
  const lines = saved.body.split('\n'); const line = lines.findIndex(l => l.startsWith('- [ ]'));
  await call('toggle_task', { id: note.id, line, completed: true, expectedRevision: saved.revision });
  const read = await call('read_note', { id: note.id }); assert.match(read.body, /- \[x\] Review/);
  const found = await call('list_notes', { query: 'Conversation', folderId: folder.id }); assert.equal(found.total, 1);
  const resource = await client.readResource({ uri: `margin://notes/${note.id}` }); assert.match(resource.contents[0].text, /We chose local storage/);
  const invalid = await client.callTool({ name: 'add_input', arguments: { id: note.id, type: 'link', text: 'bad', url: 'file:///etc/passwd' } }); assert.equal(invalid.isError, true);
  await call('trash_note', { id: note.id }); assert.equal((await call('list_notes', { query: 'Conversation', folderId: folder.id })).total, 0);
  await call('restore_note', { id: note.id }); assert.equal((await call('list_notes', { query: 'Conversation', folderId: folder.id })).total, 1);
  const history = await call('note_history', { id: note.id });
  assert.ok(history.versions.some(version => version.revision === note.revision));
  assert.equal((await call('read_note_version', { id: note.id, revision: note.revision })).note.body, 'We chose local storage.');
  assert.equal((await call('note_link', { id: note.id })).url, `margin://note/${note.id}`);
  const copy = await call('duplicate_note', { id: note.id, source: 'Claude' });
  assert.notEqual(copy.id, note.id); assert.equal(copy.source, 'Claude');
  const restoreStale = await client.callTool({ name: 'restore_note_version', arguments: { id: note.id, revision: note.revision, expectedRevision: note.revision } });
  assert.equal(restoreStale.isError, true);
  const restored = await call('restore_note_version', { id: note.id, revision: note.revision, expectedRevision: (await store.get(note.id)).revision });
  assert.equal(restored.body, 'We chose local storage.');
  assert.equal(tools.tools.find(tool => tool.name === 'restore_note_version').annotations.destructiveHint, true);
  await store.setDemoMode(true);
  assert.equal((await call('list_notes', {})).demoMode, true);
  assert.equal((await call('list_folders', {})).demoMode, true);
  const demoInput = await call('create_note', { title: 'Demo MCP input', source: 'Codex' });
  const privateRead = await client.callTool({ name: 'read_note', arguments: { id: note.id } });
  assert.equal(privateRead.isError, true);
  await store.setDemoMode(false);
  assert.equal((await call('list_notes', {})).demoMode, false);
  assert.equal((await call('list_notes', { query: 'Demo MCP input' })).total, 0);
  assert.match((await call('read_note', { id: note.id })).body, /We chose local storage/);
  await assert.rejects(() => store.get(demoInput.id), /not found/);

});
test('connection commands quote paths and Claude environment flags precede transport options', () => {
  const info = connectionInfo('/some path/Node', "/a user's files/server.mjs", '/some data', true);
  const parsed = JSON.parse(info.claudeDesktop);
  assert.equal(parsed.mcpServers.margin.env.ELECTRON_RUN_AS_NODE, '1');
  assert.match(info.claude, /--env .* --transport stdio --scope user margin --/);
  assert.match(info.codex, /'\\''/);
});
