import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { NoteStore } from '../shared/store.mjs';

test('note height migrates old data and survives reopening, content edits, folding, and Trash', async t => {
  const dir = await fs.mkdtemp(path.join(tmpdir(), 'margin-resize-'));
  t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const store = await new NoteStore(dir).init();
  const note = await store.create({ title: 'Resizable', body: 'Keep every word.', source: 'Codex' });
  await store.create({ title: 'A newer note' });
  const orderBefore = (await store.list()).notes.map(note => note.id);
  const old = await store.read(); delete old.notes[0].bodyHeight;
  await fs.writeFile(store.file, JSON.stringify(old));
  assert.equal((await store.get(note.id)).bodyHeight, null);
  await store.update(note.id, { bodyHeight: 320 });
  const reopened = await new NoteStore(dir).init();
  assert.equal((await reopened.get(note.id)).bodyHeight, 320);
  assert.equal((await reopened.get(note.id)).body, note.body);
  assert.equal((await reopened.get(note.id)).updatedAt, note.updatedAt);
  assert.deepEqual((await reopened.list()).notes.map(note => note.id), orderBefore);
  const current = await reopened.get(note.id);
  await reopened.update(note.id, { title: current.title, body: current.body, source: 'You', bodyHeight: 320, expectedRevision: current.revision });
  assert.equal((await reopened.get(note.id)).updatedAt, note.updatedAt, 'Inline height-only autosave keeps the content date');
  assert.equal((await reopened.get(note.id)).source, 'Codex');
  await reopened.append(note.id, 'A later thought.');
  await reopened.update(note.id, { collapsed: true });
  await reopened.update(note.id, { collapsed: false });
  await reopened.trash(note.id); await reopened.restore(note.id);
  assert.equal((await reopened.get(note.id)).bodyHeight, 320);
  assert.equal((await reopened.get(note.id)).body, 'Keep every word.\n\nA later thought.');
  const saved = await fs.readFile(reopened.file, 'utf8');
  for (const bodyHeight of [0, 55, 1601, 80.5, 'large']) await assert.rejects(() => reopened.update(note.id, { bodyHeight }));
  assert.equal(await fs.readFile(reopened.file, 'utf8'), saved);
  await reopened.update(note.id, { bodyHeight: null });
  assert.equal((await new NoteStore(dir).get(note.id)).bodyHeight, null);
});
