const { contextBridge, ipcRenderer, webUtils } = require('electron');
contextBridge.exposeInMainWorld('margin', {
  appearancePreferences: () => ipcRenderer.invoke('appearance:preferences').then(r => r.value),
  onAppearancePreferences: fn => { const listener = (_event, prefs) => fn(prefs); ipcRenderer.on('appearance:preferences', listener); return () => ipcRenderer.removeListener('appearance:preferences', listener); },
  snapshot: () => ipcRenderer.invoke('notes:snapshot'),
  demo: enabled => ipcRenderer.invoke('notebook:demo', enabled),
  resetNotebook: revision => ipcRenderer.invoke('notebook:reset', revision),
  create: input => ipcRenderer.invoke('notes:create', input),
  duplicate: id => ipcRenderer.invoke('notes:duplicate', id),
  history: id => ipcRenderer.invoke('notes:history', id),
  restoreVersion: (id, version, revision) => ipcRenderer.invoke('notes:restore-version', id, version, revision),
  copyLink: id => ipcRenderer.invoke('notes:copy-link', id),
  onOpenNote: fn => { const listener = (_event, id) => fn(id); ipcRenderer.on('notes:open', listener); return () => ipcRenderer.removeListener('notes:open', listener); },
  prepareImport: () => ipcRenderer.invoke('notebook:prepare-import'),
  backups: () => ipcRenderer.invoke('notebook:backups'),
  previewBackup: name => ipcRenderer.invoke('notebook:preview-backup', name),
  applyImport: (token, mode) => ipcRenderer.invoke('notebook:apply-import', token, mode),
  importMarkdown: (folderId, directory = false) => ipcRenderer.invoke('markdown:import', folderId, directory),
  dropMarkdown: (files, folderId) => ipcRenderer.invoke('markdown:drop', files.map(file => webUtils.getPathForFile(file)), folderId),
  exportMarkdown: options => ipcRenderer.invoke('markdown:export', options),
  update: (id, input) => ipcRenderer.invoke('notes:update', id, input),
  sectionAppearance: (id, input) => ipcRenderer.invoke('sections:appearance', id, input),
  chooseIcon: () => ipcRenderer.invoke('icons:choose'),
  reorderNote: (id, targetId, placement) => ipcRenderer.invoke('notes:reorder', id, targetId, placement),
  reorderTab: (id, targetId, placement) => ipcRenderer.invoke('folders:reorder', id, targetId, placement),
  trash: id => ipcRenderer.invoke('notes:trash', id),
  restore: id => ipcRenderer.invoke('notes:restore', id),
  toggleTask: (id, line, done, revision) => ipcRenderer.invoke('notes:task', id, line, done, revision),
  createFolder: (name, color) => ipcRenderer.invoke('folders:create', name, color),
  renameFolder: (id, name) => ipcRenderer.invoke('folders:rename', id, name),
  deleteFolder: id => ipcRenderer.invoke('folders:delete', id),
  settings: patch => ipcRenderer.invoke('settings:set', patch),
  vaultTheme: (refresh = false) => ipcRenderer.invoke('themes:vault', refresh),
  saveTheme: (name, id) => ipcRenderer.invoke('themes:save', name, id),
  deleteTheme: id => ipcRenderer.invoke('themes:delete', id),
  connections: () => ipcRenderer.invoke('app:connections'),
  attach: id => ipcRenderer.invoke('notes:attach', id),
  dropFiles: (id, files) => ipcRenderer.invoke('notes:drop', id, files.map(file => webUtils.getPathForFile(file))),
  openAttachment: id => ipcRenderer.invoke('app:attachment', id),
  openLink: (url, preferred) => ipcRenderer.invoke('app:link', url, preferred),
  linkMenu: url => ipcRenderer.invoke('app:link-menu', url),
  linkApps: () => ipcRenderer.invoke('app:link-apps'),
  showData: () => ipcRenderer.invoke('app:data'),
  export: () => ipcRenderer.invoke('app:export'),
  copy: text => ipcRenderer.invoke('app:copy', text),
  nativeEdit: action => ipcRenderer.invoke('app:native-edit', action),
  onEditCommand: fn => { const listener = (_event, action) => fn(action); ipcRenderer.on('app:edit-command', listener); return () => ipcRenderer.removeListener('app:edit-command', listener); },
  hide: () => ipcRenderer.invoke('app:hide'),
  panelPrepared: id => ipcRenderer.send('panel:motion-ready', id),
  panelFinished: id => ipcRenderer.send('panel:motion-finished', id),
  onPanelPrepare: fn => ipcRenderer.on('panel:motion-prepare', (_event, motion) => fn(motion)),
  onPanelStart: fn => ipcRenderer.on('panel:motion-start', (_event, id) => fn(id)),
  onPanelSettle: fn => ipcRenderer.on('panel:motion-settle', (_event, motion) => fn(motion)),
  onChange: fn => { const listener = (_event, state) => fn(state); ipcRenderer.on('notes:changed', listener); return () => ipcRenderer.removeListener('notes:changed', listener); },
  onVaultStatus: fn => { const listener = (_event, status) => fn(status); ipcRenderer.on('vault:status', listener); return () => ipcRenderer.removeListener('vault:status', listener); },
  onNew: fn => { const listener = () => fn(); ipcRenderer.on('app:new', listener); return () => ipcRenderer.removeListener('app:new', listener); }
});
