import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { clipboard, ClipboardItem } from 'electron';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { exportBackup } from '../shared/notebook-features.mjs';
export async function runSmoke(win, store, panel) {
  const priorClipboard = await Promise.all((await clipboard.read()).map(async item => new ClipboardItem(Object.fromEntries(await Promise.all(item.types.map(async type => [type, await item.getType(type)]))))));
  try {
  const run = code => win.webContents.executeJavaScript(`{ ${code} }`, true);
  const wait = async code => { for (let i = 0; i < 80; i++) { if (await run(code)) return; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`Timed out: ${code}`); };
  const click = text => run(`Array.from(document.querySelectorAll('button')).find(button => button.textContent.trim() === ${JSON.stringify(text)}).click()`);
  const label = text => run(`document.querySelector('[aria-label=${JSON.stringify(text)}]').click()`);
  const input = (selector, value) => run(`const input = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input, ${JSON.stringify(value)}); input.dispatchEvent(new Event('input', {bubbles:true}));`);
  const screenshot = async name => { const dir = process.env.MARGIN_ARTIFACTS_DIR || path.join(store.dir, 'artifacts'); await fs.mkdir(dir, { recursive: true }); await fs.writeFile(path.join(dir, name), (await win.webContents.capturePage()).toPNG()); };
  const first = await store.create({ title: 'Work decisions', body: 'Original decision\n\n- [ ] Check this', folderId: 'work', source: 'Codex' });
  await store.update(first.id, { body: 'Latest decision\n\n**needle** here\n\n' + '\n\n'.repeat(30) + 'needle at the bottom', source: 'Claude' });
  const second = await store.create({ title: 'Personal needle', body: `A second needle\n\n[Open decisions](margin://note/${first.id})`, folderId: 'personal' });
  panel.show(); await wait(`document.querySelectorAll('.note-card').length === 2`);
  await click('Work'); await input('[aria-label="Search notes"]', 'needle');
  await wait(`document.querySelectorAll('.note-card').length === 2 && document.querySelectorAll('.search-match').length >= 3`);
  await click('In Work'); await wait(`document.querySelectorAll('.note-card').length === 1`);
  await click('Jump to next match'); assert.equal(await run(`Boolean(document.querySelector('.search-match.current-match'))`), true);
  await screenshot('margin-search-scopes.png');
  await label('Clear search');
  await label('Actions for Work decisions'); await click('Copy link to note');
  await run(`window.margin.openLink('margin://note/${second.id}')`);
  await wait(`document.activeElement?.dataset.noteId === '${second.id}'`);
  assert.equal(await run(`document.querySelector('[data-note-id="${second.id}"] .note-body a').getAttribute('href')`), `margin://note/${first.id}`);
  await run(`document.querySelector('[data-note-id="${second.id}"] .note-body a').click()`);
  await wait(`document.activeElement?.dataset.noteId === '${first.id}'`);
  await label('Actions for Work decisions'); await click('Note history…');
  await wait(`document.querySelector('[aria-label="Saved version"]')?.options.length >= 2`);
  await run(`const select=document.querySelector('[aria-label="Saved version"]'); select.value='1'; select.dispatchEvent(new Event('change',{bubbles:true}));`);
  await wait(`document.querySelector('.history-preview')?.textContent.includes('Original decision')`);
  await screenshot('margin-note-history.png');
  await click('Restore this version'); await wait(`!document.querySelector('[aria-label="Note history"]')`);
  assert.equal((await store.get(first.id)).body, 'Original decision\n\n- [ ] Check this');
  await label('Actions for Work decisions'); await click('Duplicate note');
  await wait(`Boolean(document.querySelector('.editor-title'))`);
  assert.equal(await run(`document.querySelector('.editor-title').value`), 'Work decisions (copy)');
  await label('Done editing'); await wait(`!document.querySelector('.editor')`);
  const md = path.join(store.dir, 'Imported.md'); await fs.writeFile(md, '# Imported title\n\n## Subheading\n\n**Formatting**');
  const { importMarkdown } = await import('../shared/notebook-features.mjs'); await importMarkdown(store, [md]);
  await wait(`document.querySelectorAll('.note-card').length === 4`);
  await label('Preferences'); await click('Backups & import');
  await wait(`document.querySelectorAll('.backup-row').length > 0`);
  await run(`document.querySelector('.backup-row').click()`);
  await wait(`Boolean(document.querySelector('[aria-label="Backup import mode"]'))`);
  await click('Restore notebook…'); await wait(`Boolean(document.querySelector('[aria-label="Restore notebook confirmation"]'))`);
  await screenshot('margin-backup-preview.png');
  const before = await store.read(); await click('Cancel'); assert.deepEqual(await store.read(), before);
  await label('Back to notes');
  const backups = await fs.readdir(path.join(store.dir, 'backups')); assert.ok(backups.length > 0);
  assert.equal((await exportBackup(store)).notes.length, 4);
  const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
  const env = { ...process.env, MARGIN_DATA_DIR: store.dir, margin_app: process.env.MARGIN_TEST_CAPTURE_APP || path.join(root, 'release/mac-arm64/Margin Notes.app') };
  const invoke = text => promisify(execFile)('/usr/bin/osascript', ['-l', 'JavaScript', path.join(root, 'integrations/alfred/capture.js'), text], { env });
  const typed = await invoke('Typed Alfred note 📝\nSecond line'); assert.match(typed.stdout, /Saved to Inbox/);
  clipboard.writeText('Clipboard Alfred note 📝\nSecond line');
  const captured = await invoke(''); assert.match(captured.stdout, /Saved to Inbox/);
  assert.equal((await store.list({ query: 'Clipboard Alfred note' })).notes[0].body, 'Clipboard Alfred note 📝\nSecond line');
  assert.equal((await store.list({ query: 'Typed Alfred note' })).notes[0].source, 'Alfred');
  console.log('Feature smoke passed: all-folder search, scoped search, highlighted match navigation, note links, history preview and restore, duplication, Markdown imports, backup preview and restore cancellation, real Alfred typed and clipboard capture.');
  } finally { if (priorClipboard.length) await clipboard.write(priorClipboard); else clipboard.clear(); }
}
