import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ipcMain } from 'electron';
import { fileLink } from '../shared/app-links.mjs';
import { installedLinkApps } from '../app/document-links.mjs';

export async function runSmoke(win, store, panel) {
  const run = code => win.webContents.executeJavaScript(`{ ${code} }`, true);
  const wait = async code => { for (let i = 0; i < 100; i++) { if (await run(code)) return; await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error(`Timed out: ${code}`); };
  const click = label => run(`document.querySelector('[aria-label=${JSON.stringify(label)}]').click()`);
  const apps = await installedLinkApps();
  assert.ok(apps.onyx && apps.obsidian && apps.cxtasks, 'Find the installed Onyx, Obsidian, and CXTasks bundles');
  const document = path.join(store.dir, 'Design & café #2.md');
  await fs.writeFile(document, '# Linked document\n\nA local smoke-test note.');
  const href = fileLink(document);
  const body = `${document}\n\nFollow T42 and task 86.\n\n42\n\nt42 and #42\n\n[Chosen document](${href})\n\n[Obsidian note](obsidian://open?path=${encodeURIComponent(document)})\n\n[Task link](cxtasks://task/T9)\n\n\`T100\`\n\n\`\`\`text\nT101\n${document}\n\`\`\`\n\n[Unsafe](javascript:alert(1))\n\n[Unsafe Obsidian](obsidian://new?vault=Notes&file=oops)`;
  const note = await store.create({ title: 'Notes, artifacts & tasks', body });
  panel.show();
  await wait(`document.querySelector('[data-note-id="${note.id}"] .note-body a[data-link-kind="document"]')`);
  const readLinks = () => run(`Array.from(document.querySelectorAll('[data-note-id="${note.id}"] .note-body a')).map(a => ({href:a.getAttribute('href'), kind:a.dataset.linkKind, text:a.textContent}))`);
  assert.equal((await store.read()).settings.cxtasksLinks, false);
  assert.equal((await readLinks()).filter(link => link.kind === 'task').length, 0, 'Task links must be inactive by default');
  assert.equal((await run(`window.margin.openLink('T42')`)).ok, false, 'Native task opening also requires opt-in');
  await click('Preferences');
  await wait(`Boolean(document.querySelector('[aria-label="Enable CXTasks links"]'))`);
  assert.equal(await run(`document.querySelector('[aria-label="Enable CXTasks links"]').checked`), false);
  await click('Enable CXTasks links');
  await wait(`document.querySelector('[aria-label="Enable CXTasks links"]').checked`);
  assert.equal((await store.read()).settings.cxtasksLinks, true);
  await fs.mkdir(process.env.MARGIN_ARTIFACTS_DIR || path.join(store.dir, 'artifacts'), { recursive: true });
  await fs.writeFile(path.join(process.env.MARGIN_ARTIFACTS_DIR || path.join(store.dir, 'artifacts'), 'margin-cxtasks-opt-in.png'), (await win.webContents.capturePage()).toPNG());
  await click('Back to notes');
  await wait(`document.querySelectorAll('[data-note-id="${note.id}"] a[data-link-kind="task"]').length === 2`);
  const links = await readLinks();
  assert.deepEqual(links.filter(link => link.kind === 'task').map(link => link.href), ['cxtasks://task/T42', 'cxtasks://task/T9']);
  assert.equal(links.filter(link => link.kind === 'document').length, 2);
  assert.equal(links.filter(link => link.kind === 'obsidian').length, 1);
  assert.ok(!links.some(link => link.href.includes('T100') || link.href.includes('T101') || link.href.includes('javascript:') || link.href.includes('obsidian://new')));
  await run(`document.querySelector('[data-note-id="${note.id}"] a[data-link-kind="document"]').click()`);
  await wait(`!document.querySelector('.editor')`);
  for (let i = 0; !panel.linkLaunches.length && i < 80; i++) await new Promise(resolve => setTimeout(resolve, 50));
  assert.deepEqual(panel.linkLaunches.at(-1), { application: apps.onyx, value: document });
  const options = await run(`window.margin.linkMenu(${JSON.stringify(href)})`);
  assert.equal(options.ok, true); assert.deepEqual(options.value.choices.map(choice => choice.id), ['onyx', 'obsidian']);
  const obsidian = await run(`window.margin.openLink(${JSON.stringify(href)}, 'obsidian')`);
  assert.equal(obsidian.ok, true);
  assert.deepEqual(panel.linkLaunches.at(-1), { application: apps.obsidian, value: 'obsidian://open?path=' + encodeURIComponent(document) });
  await run(`document.querySelector('[data-note-id="${note.id}"] a[data-link-kind="task"]').click()`);
  for (let i = 0; panel.linkLaunches.at(-1)?.application !== apps.cxtasks && i < 80; i++) await new Promise(resolve => setTimeout(resolve, 50));
  assert.deepEqual(panel.linkLaunches.at(-1), { application: apps.cxtasks, value: 'cxtasks://task/T42' });
  assert.equal((await run(`window.margin.openLink('cxtasks://run/T42')`)).ok, false);
  assert.equal((await run(`window.margin.openLink('obsidian://new?vault=Notes&file=oops')`)).ok, false);
  assert.equal((await run(`window.margin.openLink('file:///tmp/nonexistent-margin-note.md')`)).ok, false);
  assert.equal((await store.get(note.id)).body, body, 'Recognizing a reference must not rewrite the saved note');
  const output = process.env.MARGIN_ARTIFACTS_DIR || path.join(store.dir, 'artifacts'); await fs.mkdir(output, { recursive: true });
  await fs.writeFile(path.join(output, 'margin-document-task-links.png'), (await win.webContents.capturePage()).toPNG());
  await run(`document.querySelector('[data-note-id="${note.id}"] .card-title').click()`);
  await wait(`Boolean(document.querySelector('.rich-body')?.editor)`);
  await run(`const ed=document.querySelector('.rich-body').editor; ed.commands.setContent('Chosen document',{contentType:'markdown'}); ed.chain().focus().setTextSelection({from:1,to:16}).run();`);
  await wait(`Boolean(document.querySelector('[aria-label="Edit link"]'))`);
  await click('Edit link'); await wait(`Boolean(document.querySelector('[aria-label="Link URL"]'))`);
  const input = value => run(`const input=document.querySelector('[aria-label="Link URL"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(value)}); input.dispatchEvent(new Event('input',{bubbles:true}));`);
  await input(document); await click('Apply link');
  await wait(`document.querySelector('.rich-body a')?.getAttribute('href') === ${JSON.stringify(href)}`);
  await run(`const ed=document.querySelector('.rich-body').editor; ed.chain().focus().setTextSelection({from:1,to:16}).run();`);
  await click('Edit link'); await wait(`Boolean(document.querySelector('[aria-label="Link URL"]'))`);
  await input('86'); await click('Apply link');
  await wait(`document.querySelector('.bubble-link [role="alert"]')?.textContent.includes('uppercase T')`);
  assert.equal(await run(`document.querySelector('.rich-body a')?.getAttribute('href')`), href);
  await input('T86'); await click('Apply link');
  await wait(`document.querySelector('.rich-body a')?.getAttribute('href') === 'cxtasks://task/T86'`);
  await click('Done editing');
  await wait(`!document.querySelector('.editor')`);
  assert.match((await store.get(note.id)).body, /cxtasks:\/\/task\/T86/);
  await click('Preferences'); await wait(`Boolean(document.querySelector('[aria-label="Enable CXTasks links"]'))`);
  await click('Enable CXTasks links'); await wait(`!document.querySelector('[aria-label="Enable CXTasks links"]').checked`);
  await click('Back to notes');
  await wait(`!document.querySelector('[data-note-id="${note.id}"] a[data-link-kind="task"]')`);
  assert.equal((await run(`window.margin.openLink('T86')`)).ok, false);
  // Simulate CXTasks being absent without uninstalling the user's application.
  ipcMain.removeHandler('app:link-apps');
  ipcMain.handle('app:link-apps', () => ({ ok: true, value: { cxtasks: false } }));
  await click('Preferences');
  await run(`window.dispatchEvent(new Event('focus'))`);
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.equal(await run(`Boolean(document.querySelector('[aria-label="Enable CXTasks links"]'))`), false, 'Do not surface the integration when CXTasks is absent');
  console.log('Link smoke passed: installed-app detection, plain file paths, named document links, Obsidian URIs, strict uppercase T-number references, default-off integration, installed-app-only preference, opt-in and opt-out, code exclusion, safe URL handling, app routing through IPC, both-app choices, editor document/task links, and saved Markdown.');
}
