import assert from 'node:assert/strict';
import { Menu, clipboard, ClipboardItem } from 'electron';

// Integration checks use an isolated smoke notebook, the real native menu,
// renderer, Markdown storage, and stdio MCP client.
export async function richSmoke({ win, store, client, run, waitFor, click, screenshot }) {
  const priorClipboard = await Promise.all((await clipboard.read()).map(async item => new ClipboardItem(Object.fromEntries(await Promise.all(item.types.map(async type => [type, await item.getType(type)]))))));
  try {
  const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
  const menuEdit = action => Menu.getApplicationMenu().getMenuItemById(action).click();
  const shortcut = (keyCode, modifiers) => {
    win.focus();
    win.webContents.sendInputEvent({ type: 'keyDown', keyCode, modifiers });
    win.webContents.sendInputEvent({ type: 'keyUp', keyCode, modifiers });
  };
  const create = async (title, body) => {
    const result = await client.callTool({ name: 'create_note', arguments: { title, body, source: 'Codex' } });
    assert.ok(!result.isError, result.content?.[0]?.text);
    const note = JSON.parse(result.content[0].text);
    await waitFor(`Boolean(document.querySelector('[data-note-id="${note.id}"]'))`);
    return note;
  };
  const open = async note => {
    await run(`document.querySelector('[data-note-id="${note.id}"] .card-title').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
    await waitFor(`Boolean(document.querySelector('.rich-body')?.editor)`);
  };
  const select = async (text, collapse = false) => { win.focus(); await run(`
    const ed = document.querySelector('.rich-body').editor;
    let found;
    ed.state.doc.descendants((node, pos) => { if (found == null && node.isText && node.text.includes(${JSON.stringify(text)})) found = pos + node.text.indexOf(${JSON.stringify(text)}); });
    if (found == null) throw new Error('Selection text not found');
    ed.chain().focus().setTextSelection({from:found + ${collapse ? text.length : 0},to:found + ${text.length}}).run();
  `); await waitFor(`document.activeElement === document.querySelector('.rich-body')`); };
  const visibleToolbar = `document.querySelector('.format-bubble')?.getClientRects().length && getComputedStyle(document.querySelector('.format-bubble')).visibility === 'visible'`;
  const markdown = () => run(`document.querySelector('.rich-body').editor.getMarkdown()`);
  const original = '# Heading\n\nA quiet thought for today.\n\n- [ ] A task\n- [x] Finished task\n\n<u>Underlined <mark>and highlighted</mark></u>\n\n| Name | Value |\n| --- | --- |\n| One | Two |\n\n![Remote picture](https://example.com/image.png)\n\n```js\nconst answer = 42;\n```'.replace('\n\n```js', '\n\n' + Array.from({length:18},()=> 'A little more room for thoughts.').join('\n\n') + '\n\n```js');
  const note = await create('Rich text checks', original);
  await run(`window.margin.settings({themeId:'cxtasks-glass',theme:'dark'})`);
  await open(note);
  assert.equal(await run(`Boolean(document.querySelector('.overlay.editor, .write-tabs, .editor-source, .editor-preview'))`), false, 'Editing stays in the card with one live Markdown surface');
  assert.equal(await run(`document.querySelector('.editor').parentElement.className`), 'notes-scroll');
  assert.ok(await run(`document.querySelectorAll('.note-card').length > 1`), 'Neighbouring notes remain in the notebook');
  assert.equal(await run(`Boolean(document.querySelector('.editor-hint, .save-button, .editor-footer'))`), false, 'Autosave replaces manual save and editor tips');
  assert.equal(await run(`getComputedStyle(document.querySelector('.rich-body mark')).backgroundColor`), 'rgb(242, 212, 107)');
  assert.equal(await run(`getComputedStyle(document.querySelector('.rich-body mark')).color`), 'rgb(33, 27, 8)');
  assert.equal(await run(`document.querySelectorAll('.rich-body li[data-type="taskItem"]').length`), 2);
  assert.equal(await run(`Boolean(document.querySelector('.rich-body table'))`), true);
  assert.equal(await run(`Boolean(document.querySelector('.rich-body img'))`), false, 'Editing must not fetch remote images');
  assert.equal(await run(`Boolean(document.querySelector('.rich-body u mark'))`), true, 'Nested inline formatting must parse from saved Markdown');
  assert.match(await markdown(), /- \[x\] Finished task/);
  assert.match(await markdown(), /!\[Remote picture\]\(https:\/\/example.com\/image.png\)/);
  // Merely opening a note must not normalize or dirty its Markdown.
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  assert.equal((await store.get(note.id)).body, original);
  await open(note);
  await run(`const title = document.querySelector('.editor-title'); title.focus(); title.setSelectionRange(title.value.length,title.value.length)`);
  win.webContents.insertText(' edited');
  await waitFor(`document.querySelector('.editor-title').value === 'Rich text checks edited'`);
  await waitFor(`!document.querySelector('.note-caret').hidden && document.querySelector('.editor-title').classList.contains('has-note-caret')`);
  assert.equal(await run(`document.querySelector('.note-caret').getBoundingClientRect().width`), 2, 'Title caret has a wider rounded stroke');
  assert.equal(await run(`getComputedStyle(document.querySelector('.note-caret')).borderRadius`), '1px');
  menuEdit('undo');
  await waitFor(`document.querySelector('.editor-title').value === 'Rich text checks'`);
  menuEdit('redo');
  await waitFor(`document.querySelector('.editor-title').value === 'Rich text checks edited'`);
  menuEdit('undo');
  await waitFor(`document.querySelector('.editor-title').value === 'Rich text checks'`);
  await run(`const checkbox=document.querySelector('.rich-body li[data-checked="false"] input'); checkbox.click()`);
  await waitFor(`document.querySelector('.rich-body li').dataset.checked === 'true' && document.activeElement === document.querySelector('.rich-body')`);
  await run(`document.querySelector('.rich-body li input').focus()`);
  menuEdit('undo');
  await waitFor(`document.querySelector('.rich-body li').dataset.checked === 'false'`);
  menuEdit('redo');
  await waitFor(`document.querySelector('.rich-body li').dataset.checked === 'true'`);
  menuEdit('undo');
  await waitFor(`document.querySelector('.rich-body li').dataset.checked === 'false'`);
  await select('A quiet thought for today.', true);
  await waitFor(`!document.querySelector('.note-caret').hidden && document.querySelector('.rich-body').classList.contains('has-note-caret')`);
  const caretPosition = await run(`const cursor=document.querySelector('.note-caret').getBoundingClientRect(); const ed=document.querySelector('.rich-body').editor; const native=ed.view.coordsAtPos(ed.state.selection.from); ({width:cursor.width,left:cursor.left + cursor.width / 2,top:cursor.top,nativeLeft:native.left,nativeTop:native.top})`);
  assert.equal(caretPosition.width, 2);
  assert.ok(Math.abs(caretPosition.left - caretPosition.nativeLeft) < 1 && Math.abs(caretPosition.top - caretPosition.nativeTop) < 1, 'Thicker caret follows the true insertion position');
  await run(`document.querySelector('.note-caret').getAnimations().forEach(animation => { animation.pause(); animation.currentTime=0; })`);
  await screenshot('margin-thicker-caret.png');
  await run(`document.querySelector('.note-caret').getAnimations().forEach(animation => animation.play())`);
  await run(`document.querySelector('.rich-body').dispatchEvent(new CompositionEvent('compositionstart', {bubbles:true}))`);
  assert.equal(await run(`document.querySelector('.note-caret').hidden && !document.querySelector('.rich-body').classList.contains('has-note-caret')`), true, 'Composition keeps the native caret');
  await run(`document.querySelector('.rich-body').dispatchEvent(new CompositionEvent('compositionend', {bubbles:true}))`);
  await waitFor(`!document.querySelector('.note-caret').hidden`);
  win.webContents.insertText(' Extra words');
  await waitFor(`document.querySelector('.rich-body').textContent.includes('Extra words')`);
  shortcut('Z', ['meta']);
  await waitFor(`!document.querySelector('.rich-body').textContent.includes('Extra words')`);
  shortcut('Z', ['meta', 'shift']);
  await waitFor(`document.querySelector('.rich-body').textContent.includes('Extra words')`);
  menuEdit('undo');
  await waitFor(`!document.querySelector('.rich-body').textContent.includes('Extra words')`);
  await select('A quiet thought for today.');
  await waitFor(`document.querySelector('.note-caret').hidden`);
  await waitFor(visibleToolbar);
  await click('Copy selected text');
  await pause(100);
  assert.equal(await clipboard.readText(), 'A quiet thought for today.');
  const hover = async (label, expected = label) => {
    win.focus();
    await waitFor(`document.hasFocus()`);
    await waitFor(visibleToolbar);
    await pause(100);
    const selector = `.format-bubble [aria-label=${JSON.stringify(label)}]`;
    win.webContents.sendInputEvent({type:'mouseMove',x:0,y:0});
    const point = await run(`const b=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect(); ({x:b.left+b.width/2,y:b.top+b.height/2})`);
    win.webContents.sendInputEvent({type:'mouseMove',x:Math.round(point.x),y:Math.round(point.y)});
    await waitFor(`document.querySelector('[role="tooltip"]')?.textContent === ${JSON.stringify(expected)}`);
    const bounds = await run(`const t=document.querySelector('[role="tooltip"]'); const b=t.getBoundingClientRect(); ({left:b.left,right:b.right,top:b.top,bottom:b.bottom,width:innerWidth,height:innerHeight,visibility:getComputedStyle(t).visibility})`);
    assert.equal(bounds.visibility, 'visible');
    assert.ok(bounds.left >= 0 && bounds.right <= bounds.width && bounds.top >= 0 && bounds.bottom <= bounds.height, `${label} tooltip fits in the panel`);
  };
  for (const [label, keys] of [['Copy selected text','⌘C'],['Lists',''],['Text style',''],['Blockquote','⌘⇧B'],['Bold','⌘B'],['Italic','⌘I'],['Highlight','⌘⇧H'],['Strikethrough','⌘⇧S'],['Underline','⌘U'],['Edit link','⌘K'],['Inline code','⌘E'],['Code block','⌘⌥C'],['Clear formatting','⌘\\']]) await hover(label, label + keys);
  await hover('Bold', 'Bold⌘B');
  await screenshot('margin-formatting-shortcuts.png');
  win.focus();
  await waitFor(visibleToolbar);
  assert.equal(await run(`const ed=document.querySelector('.rich-body').editor; ed.state.doc.textBetween(ed.state.selection.from,ed.state.selection.to)`), 'A quiet thought for today.', 'Hovering toolbar items preserves the selected text');
  assert.equal(await run(`document.querySelector('.format-bubble [aria-label="Bold"]').getAttribute('aria-keyshortcuts')`), 'Meta+B');
  shortcut('B', ['meta']);
  await waitFor(`document.querySelector('.rich-body').editor.isActive('bold')`);
  assert.match(await markdown(), /\*\*A quiet thought for today\.\*\*/);
  menuEdit('undo');
  await waitFor(`!document.querySelector('.rich-body').editor.isActive('bold')`);
  menuEdit('redo');
  await waitFor(`document.querySelector('.rich-body').editor.isActive('bold')`);
  for (const [key, modifiers, mark] of [['I',['meta'],'italic'],['H',['meta','shift'],'highlight'],['U',['meta'],'underline'],['S',['meta','shift'],'strike']]) {
    shortcut(key, modifiers);
    await waitFor(`document.querySelector('.rich-body').editor.isActive('${mark}')`);
  }
  shortcut('K', ['meta']);
  await waitFor(`Boolean(document.querySelector('[aria-label="Link URL"]'))`);
  await waitFor(`document.activeElement === document.querySelector('[aria-label="Link URL"]')`);
  await hover('Apply link', 'Apply linkEnter');
  await run(`const input=document.querySelector('[aria-label="Link URL"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'example.com'); input.dispatchEvent(new Event('input',{bubbles:true}));`);
  shortcut('Return', []);
  await waitFor(`Boolean(document.querySelector('.rich-body a[href="https://example.com"]'))`);
  await select('A quiet thought for today.');
  await waitFor(visibleToolbar);
  await pause(200);
  const bounds = await run(`const b=document.querySelector('.format-bubble').getBoundingClientRect(); ({left:b.left,right:b.right,top:b.top,bottom:b.bottom,width:innerWidth,height:innerHeight})`);
  assert.ok(bounds.left >= 0 && bounds.right <= bounds.width && bounds.top >= 0 && bounds.bottom <= bounds.height, 'Selection toolbar must fit inside the edge panel');
  const scrollBefore = await run(`document.querySelector('.editor-scroll').scrollTop`);
  await run(`document.querySelector('.editor-scroll').scrollTop += 30`);
  await pause(200);
  const afterScroll = await run(`document.querySelector('.format-bubble').getBoundingClientRect().top`);
  const scrollDelta = await run(`document.querySelector('.editor-scroll').scrollTop`) - scrollBefore;
  assert.ok(scrollDelta > 0 && Math.abs(afterScroll - bounds.top + scrollDelta) < 4, `Toolbar must follow the selection when the editor scrolls (before ${bounds.top}, after ${afterScroll}, scroll ${scrollDelta})`);
  await run(`document.querySelector('.editor-scroll').scrollTop -= 30`); await pause(150);
  await screenshot('margin-rich-toolbar.png');
  await click('Clear formatting');
  assert.equal(await run(`Boolean(document.querySelector('.rich-body p a'))`), false);
  menuEdit('undo');
  await waitFor(`Boolean(document.querySelector('.rich-body p a'))`);
  await click('Text style'); await click('Heading 2');
  await waitFor(`Boolean(document.querySelector('.rich-body h2'))`);
  await screenshot('margin-rich-heading.png');
  await click('Text style'); await click('Paragraph');
  await click('Blockquote');
  assert.equal(await run(`Boolean(document.querySelector('.rich-body blockquote'))`), true);
  await click('Blockquote');
  await click('Lists'); await click('Checklist');
  assert.equal(await run(`document.querySelectorAll('.rich-body li[data-type="taskItem"]').length`), 3);
  await click('Lists'); await click('Checklist');
  await select('A task'); await click('Inline code');
  assert.match(await markdown(), /`A task`/);
  await select('const answer = 42;');
  await waitFor(visibleToolbar);
  await click('Code block');
  assert.equal(await run(`Boolean(document.querySelector('.rich-body pre'))`), false);
  await click('Code block');
  await waitFor(`Boolean(document.querySelector('.rich-body pre'))`);
  const formatted = await markdown();
  assert.match(formatted, /<u>/); assert.match(formatted, /<mark>/); assert.match(formatted, /https:\/\/example.com/);
  await screenshot('margin-inline-editing.png');
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  const saved = await store.get(note.id);
  assert.match(saved.body, /<u>/); assert.match(saved.body, /<mark>/); assert.match(saved.body, /- \[x\] Finished task/);
  const mcp = await client.callTool({name:'read_note',arguments:{id:note.id}});
  assert.equal(JSON.parse(mcp.content[0].text).body, saved.body);
  await open(note);
  assert.equal(await run(`Boolean(document.querySelector('.rich-body u mark, .rich-body mark u'))`), true);
  assert.equal(await run(`document.querySelector('[aria-label="Undo"]').disabled`), true, 'Saved editing sessions start fresh history');
  await click('Done editing'); await waitFor(`!document.querySelector('.editor')`);
  // Actual desktop shortcuts also work at a caret and in every block style.
  const keyboardNote = await create('Keyboard shortcuts', 'Keyboard sample');
  await open(keyboardNote);
  const resetKeyboardNote = async () => {
    await run(`document.querySelector('.rich-body').editor.commands.setContent('Keyboard sample', {contentType:'markdown'}); document.querySelector('.rich-body').editor.commands.focus('end')`);
    await waitFor(`document.activeElement === document.querySelector('.rich-body')`);
    shortcut('A', ['meta']);
    await waitFor(`const ed=document.querySelector('.rich-body').editor; ed.state.doc.textBetween(ed.state.selection.from,ed.state.selection.to) === 'Keyboard sample'`);
  };
  await resetKeyboardNote();
  win.webContents.copy();
  await pause(100);
  assert.equal(await clipboard.readText(), 'Keyboard sample');
  win.webContents.cut();
  await waitFor(`document.querySelector('.rich-body').editor.isEmpty`);
  win.webContents.paste();
  await waitFor(`document.querySelector('.rich-body').textContent === 'Keyboard sample'`);
  for (const [key, modifiers, node, attrs] of [
    ['B',['meta','shift'],'blockquote'], ['E',['meta'],'code'], ['C',['meta','alt'],'codeBlock'],
    ['8',['meta','shift'],'bulletList'], ['7',['meta','shift'],'orderedList'], ['9',['meta','shift'],'taskList'],
    ...[1,2,3,4,5,6].map(level => [String(level),['meta','alt'],'heading',{level}])
  ]) {
    await resetKeyboardNote();
    shortcut(key, modifiers);
    await waitFor(`document.querySelector('.rich-body').editor.isActive(${JSON.stringify(node)}, ${JSON.stringify(attrs || {})})`);
  }
  shortcut('0', ['meta','alt']);
  await waitFor(`document.querySelector('.rich-body').editor.isActive('paragraph') && !document.querySelector('.rich-body h6')`);
  await resetKeyboardNote();
  shortcut('B', ['meta']);
  await waitFor(`document.querySelector('.rich-body').editor.isActive('bold')`);
  shortcut('\\', ['meta']);
  await waitFor(`!document.querySelector('.rich-body').editor.isActive('bold')`);
  await run(`document.querySelector('.rich-body').editor.commands.focus('end')`);
  shortcut('B', ['meta']);
  await waitFor(`document.querySelector('.rich-body').editor.isActive('bold')`);
  await win.webContents.insertText(' Bold at caret');
  await waitFor(`document.querySelector('.rich-body strong')?.textContent === ' Bold at caret'`);
  shortcut('B', ['meta']);
  await win.webContents.insertText(' Plain again');
  await waitFor(`document.querySelector('.rich-body').textContent.includes('Plain again') && !document.querySelector('.rich-body strong').textContent.includes('Plain again')`);
  await resetKeyboardNote();
  await waitFor(visibleToolbar);
  await click('Lists');
  for (const [label, keys] of [['Bullet list','⌘⇧8'],['Numbered list','⌘⇧7'],['Checklist','⌘⇧9']]) await hover(label, label + keys);
  await click('Text style');
  await hover('Paragraph', 'Paragraph⌘⌥0');
  for (const level of [1,2,3,4,5,6]) await hover(`Heading ${level}`, `Heading ${level}⌘⌥${level}`);
  shortcut('K', ['meta']);
  await waitFor(`document.activeElement === document.querySelector('[aria-label="Link URL"]')`);
  await win.webContents.insertText('javascript:alert(1)');
  shortcut('Return', []);
  await waitFor(`Boolean(document.querySelector('.bubble-link [role="alert"]'))`);
  assert.equal(await markdown(), 'Keyboard sample');
  shortcut('Escape', []);
  await waitFor(`!document.querySelector('.bubble-link') && document.activeElement === document.querySelector('.rich-body')`);
  assert.equal(await run(`Boolean(document.querySelector('.editor'))`), true, 'Escape dismisses the link field without closing the editor');
  shortcut('K', ['meta']);
  await waitFor(`document.activeElement === document.querySelector('[aria-label="Link URL"]')`);
  await win.webContents.insertText('example.com/keyboard');
  shortcut('Return', []);
  await waitFor(`document.querySelector('.rich-body a')?.textContent === 'Keyboard sample'`);
  await select('Keyboard sample');
  await run(`const ed=document.querySelector('.rich-body').editor; ed.commands.setTextSelection(ed.state.selection.from + 4)`);
  shortcut('K', ['meta']);
  await waitFor(`document.activeElement === document.querySelector('[aria-label="Link URL"]') && document.querySelector('[aria-label="Link URL"]').value === 'https://example.com/keyboard'`);
  await hover('Remove link', 'Remove link⌘⇧K');
  await win.webContents.insertText('example.com/updated');
  shortcut('Return', []);
  await waitFor(`document.querySelector('.rich-body a')?.getAttribute('href') === 'https://example.com/updated'`);
  await waitFor(`!document.querySelector('.bubble-link') && document.activeElement === document.querySelector('.rich-body')`);
  assert.equal(await run(`document.querySelector('.rich-body').textContent`), 'Keyboard sample', 'Editing a link at the caret preserves its text');
  shortcut('K', ['meta','shift']);
  await waitFor(`!document.querySelector('.rich-body a')`);
  await run(`document.querySelector('.rich-body').editor.commands.focus('end')`);
  await waitFor(`document.activeElement === document.querySelector('.rich-body') && document.querySelector('.rich-body').editor.state.selection.empty`);
  shortcut('K', ['meta']);
  await waitFor(`document.activeElement === document.querySelector('[aria-label="Link URL"]')`);
  await waitFor(visibleToolbar);
  await win.webContents.insertText('example.com/inserted');
  shortcut('Return', []);
  await waitFor(`document.querySelector('.rich-body a')?.getAttribute('href') === 'https://example.com/inserted'`);
  await waitFor(`!document.querySelector('.bubble-link') && document.activeElement === document.querySelector('.rich-body')`);
  await win.webContents.insertText(' after link');
  await waitFor(`document.querySelector('.rich-body').textContent.endsWith(' after link')`);
  assert.equal(await run(`document.querySelector('.rich-body a').textContent`), 'example.com/inserted', 'Typing after an inserted link returns to plain text');
  await click('Done editing'); await waitFor(`!document.querySelector('.editor')`);
  assert.match((await store.get(keyboardNote.id)).body, /\[example\.com\/inserted\]\(https:\/\/example\.com\/inserted\) after link/);
  // Native undo must also work outside the note editor.
  await run(`document.querySelector('[aria-label="Search notes"]').focus()`);
  win.webContents.insertText('Rich text checks');
  await waitFor(`document.querySelectorAll('.note-card').length === 1`);
  menuEdit('undo');
  await waitFor(`document.querySelector('[aria-label="Search notes"]').value === ''`);
  // Inline HTML is sanitized in the reading view while u/mark are preserved.
  const safe = await create('Safe reading', '<u>Underline</u> <mark>Highlight</mark>\n\n<script>window.unsafeMarkdown = true</script>\n\n[Unsafe link](javascript:alert(1))');
  assert.equal(await run(`Boolean(document.querySelector('[data-note-id="${safe.id}"] u'))`), true);
  assert.equal(await run(`Boolean(document.querySelector('[data-note-id="${safe.id}"] script')) || Boolean(window.unsafeMarkdown)`), false);
  assert.equal(await run(`document.querySelector('[data-note-id="${safe.id}"] a')?.getAttribute('href') || ''`), '');
  // Autosave creates a single note while leaving the editor and undo history open.
  await click('New note');
  await waitFor(`Boolean(document.querySelector('.rich-body')?.editor)`);
  await run(`const input=document.querySelector('.editor-title'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Autosave check'); input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('.rich-body').editor.commands.insertContent('First thought');`);
  await waitFor(`document.querySelector('.editor-save-status').textContent === 'Saved'`);
  assert.equal(await run(`Boolean(document.querySelector('.editor'))`), true);
  assert.equal(await run(`document.querySelector('[aria-label="Undo"]').disabled`), false, 'Autosave preserves the current editing session');
  const automatic = (await store.list({query:'Autosave check'})).notes;
  assert.equal(automatic.length, 1);
  assert.equal(automatic[0].body, 'First thought');
  await run(`document.querySelector('.rich-body').editor.commands.insertContent(', with the last words');`);
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  assert.equal((await store.get(automatic[0].id)).body, 'First thought, with the last words', 'Leaving immediately flushes the last keystrokes');
  assert.equal((await store.list({query:'Autosave check'})).notes.length, 1);
  await open(automatic[0]);
  await run(`document.querySelector('.rich-body').editor.commands.setContent('Inline autosave', {contentType:'markdown'});`);
  await waitFor(`document.querySelector('.editor-save-status').textContent === 'Saved'`);
  assert.equal((await store.get(automatic[0].id)).body, 'Inline autosave');
  // A concurrent assistant write must never be silently overwritten.
  await store.update(automatic[0].id, {body:'Assistant change',source:'Codex'});
  await run(`document.querySelector('.rich-body').editor.commands.setContent('My conflicting draft', {contentType:'markdown'});`);
  await waitFor(`Boolean(document.querySelector('.editor-error'))`);
  assert.equal((await store.get(automatic[0].id)).body, 'Assistant change');
  await run(`Array.from(document.querySelectorAll('.editor-error button')).find(button => button.textContent === 'Save draft as new').click()`);
  await waitFor(`document.querySelector('.editor-save-status').textContent === 'Saved'`);
  assert.equal((await store.list({query:'My conflicting draft'})).notes.length, 1);
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  // Exercise actual typed Markdown input rules, without formatting commands.
  const live = await create('Live Markdown', '');
  await open(live);
  await run(`document.querySelector('.rich-body').editor.commands.focus('end')`);
  await waitFor(`document.activeElement === document.querySelector('.rich-body')`);
  const type = async text => { for (const char of text) await win.webContents.insertText(char); };
  await type('# Heading');
  await waitFor(`document.querySelector('.rich-body h1')?.textContent === 'Heading'`);
  shortcut('Return', []);
  await waitFor(`document.querySelector('.rich-body').editor.state.selection.$from.parent.type.name === 'paragraph'`);
  await type('**Bold** and *italic*');
  await waitFor(`document.querySelector('.rich-body strong')?.textContent === 'Bold' && document.querySelector('.rich-body em')?.textContent === 'italic'`);
  shortcut('Return', []);
  await waitFor(`document.querySelector('.rich-body').editor.state.selection.$from.parentOffset === 0`);
  await type('- [ ] Task');
  await waitFor(`document.querySelector('.rich-body li[data-type="taskItem"] > div p')?.textContent === 'Task'`);
  await waitFor(`document.querySelector('.editor-save-status').textContent === 'Saved'`);
  await screenshot('margin-live-markdown.png');
  assert.match((await store.get(live.id)).body, /^# Heading/);
  // Escape saves the inline card and leaves the native notebook open.
  await run(`document.querySelector('.rich-body').editor.commands.focus('end')`);
  await waitFor(`document.activeElement === document.querySelector('.rich-body')`);
  shortcut('Escape', []);
  await waitFor(`!document.querySelector('.editor')`);
  assert.ok(win.isVisible());
  await open(live);
  await run(`const ed=document.querySelector('.rich-body').editor; ed.commands.selectAll(); const data=new DataTransfer(); data.setData('text/plain',${JSON.stringify('# Pasted heading\n\n**Pasted bold**\n\n- [ ] Pasted task')}); ed.view.dom.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));`);
  await waitFor(`document.querySelector('.rich-body h1')?.textContent === 'Pasted heading' && document.querySelector('.rich-body strong')?.textContent === 'Pasted bold'`);
  // Clicking outside flushes immediately, including when search changes.
  await run(`document.querySelector('[aria-label="Search notes"]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));`);
  await waitFor(`!document.querySelector('.editor')`);
  assert.match((await store.get(live.id)).body, /Pasted bold/);
  // The native New Note shortcut works from search and flushes an active draft.
  const newNoteItem = Menu.getApplicationMenu().getMenuItemById('new-note');
  assert.equal(newNoteItem.accelerator, 'CmdOrCtrl+N');
  await run(`document.querySelector('[aria-label="Search notes"]').focus()`);
  shortcut('N', ['meta']);
  await waitFor(`document.querySelector('.editor-title')?.value === '' && document.activeElement === document.querySelector('.editor-title')`);
  await win.webContents.insertText('Shortcut note');
  await waitFor(`document.querySelector('.editor-title').value === 'Shortcut note'`);
  shortcut('Return', []);
  await waitFor(`document.activeElement === document.querySelector('.rich-body')`);
  await win.webContents.insertText('Saved before the next note');
  shortcut('N', ['meta']);
  await waitFor(`document.querySelector('.editor-title')?.value === '' && document.activeElement === document.querySelector('.editor-title')`);
  const shortcutNotes = (await store.list({query:'Shortcut note'})).notes;
  assert.equal(shortcutNotes.length, 1);
  assert.equal(shortcutNotes[0].body, 'Saved before the next note');
  assert.equal(await run(`document.querySelectorAll('.editor').length`), 1);
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  await click('Preferences');
  await waitFor(`Boolean(document.querySelector('.overlay[aria-label="Preferences"]'))`);
  newNoteItem.click();
  await waitFor(`!document.querySelector('.overlay') && document.querySelector('.editor-title')?.value === '' && document.activeElement === document.querySelector('.editor-title')`);
  await click('Done editing');
  await waitFor(`!document.querySelector('.editor')`);
  // Real pointer capture resizes a note without selecting text or reordering it.
  const sized = await create('Resizable note', Array.from({length:24}, (_, i) => `Thought ${i + 1}: keep these words.`).join('\n\n'));
  const sizedCard = `[data-note-id="${sized.id}"]`;
  const bodyHeight = () => run(`document.querySelector('${sizedCard} .note-body').getBoundingClientRect().height`);
  const orderBefore = (await store.read()).noteOrder;
  const heightSaved = height => waitFor(`window.margin.snapshot().then(result => result.value.notes.find(note => note.id === '${sized.id}')?.bodyHeight === ${height})`);
  const pointer = (type, x, y, down = false) => win.webContents.sendInputEvent({type, x:Math.round(x), y:Math.round(y), button:'left', clickCount:1, modifiers:down ? ['leftButtonDown'] : []});
  const resizeNote = async (delta, cancelled = false) => {
    await run(`document.querySelector('${sizedCard}').scrollIntoView({block:'start'})`);
    await pause(100);
    const start = await run(`const handle=document.querySelector('${sizedCard} .note-resize-handle').getBoundingClientRect(); ({x:handle.left + handle.width / 2,y:handle.top + handle.height / 2,height:document.querySelector('${sizedCard} .note-body').getBoundingClientRect().height})`);
    pointer('mouseMove', start.x, start.y);
    pointer('mouseDown', start.x, start.y);
    await waitFor(`document.documentElement.classList.contains('is-resizing-note')`);
    pointer('mouseMove', start.x, start.y + delta, true);
    await waitFor(`Math.abs(document.querySelector('${sizedCard} .note-body').getBoundingClientRect().height - ${Math.round(start.height + delta)}) < 1`);
    assert.deepEqual((await store.read()).noteOrder, orderBefore);
    if (cancelled) shortcut('Escape', []);
    pointer('mouseUp', start.x, start.y + delta);
    await waitFor(`!document.documentElement.classList.contains('is-resizing-note')`);
    return Math.round(start.height + delta);
  };
  const grown = await resizeNote(80);
  await waitFor(`document.querySelector('${sizedCard} .note-body').style.height === '${grown}px'`);
  await heightSaved(grown);
  assert.equal((await store.get(sized.id)).bodyHeight, grown);
  assert.equal((await store.get(sized.id)).body, sized.body, 'Reading-mode resizing preserves all content');
  assert.equal((await store.get(sized.id)).updatedAt, sized.updatedAt);
  assert.equal(await run(`Boolean(document.querySelector('.editor, .is-dragging, .drop-before, .drop-after'))`), false);
  await run(`document.querySelector('${sizedCard} [aria-label="Fold note"]').click()`);
  await waitFor(`!document.querySelector('${sizedCard} .note-body') && !document.querySelector('${sizedCard} .note-resize-handle')`);
  await run(`document.querySelector('${sizedCard} [aria-label="Expand note"]').click()`);
  await waitFor(`document.querySelector('${sizedCard} .note-body')?.style.height === '${grown}px'`);
  await open(await store.get(sized.id));
  assert.equal(await bodyHeight(), grown);
  const editedHeight = await resizeNote(-60);
  await waitFor(`document.querySelector('.editor-save-status').textContent === 'Saved'`);
  assert.equal((await store.get(sized.id)).bodyHeight, editedHeight);
  assert.equal(await run(`Boolean(document.querySelector('.editor'))`), true, 'Resizing leaves inline editing open');
  await screenshot('margin-resizable-note.png');
  await click('Done editing'); await waitFor(`!document.querySelector('.editor')`);
  assert.equal(await bodyHeight(), editedHeight);
  await resizeNote(40, true);
  await waitFor(`document.querySelector('${sizedCard} .note-body').style.height === '${editedHeight}px'`);
  assert.equal((await store.get(sized.id)).bodyHeight, editedHeight, 'Escape cancels a drag without saving the preview');
  assert.ok(win.isVisible());
  await run(`document.querySelector('${sizedCard} .note-resize-handle').focus()`);
  shortcut('Up', []);
  await waitFor(`document.querySelector('${sizedCard} .note-body').style.height === '${editedHeight - 20}px'`);
  await heightSaved(editedHeight - 20);
  assert.equal((await store.get(sized.id)).bodyHeight, editedHeight - 20);
  await run(`document.querySelector('${sizedCard} .note-resize-handle').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
  await waitFor(`document.querySelector('${sizedCard} .note-body').style.height === ''`);
  await heightSaved(null);
  assert.equal((await store.get(sized.id)).bodyHeight, null);
  await run(`window.margin.settings({themeId:'default',theme:'system'})`);
  console.log('Rich editor smoke passed: native formatting shortcuts, every toolbar tooltip, selected-text and caret link editing/insertion/removal, native Cmd N creation from search and Preferences, draft flushing before the next note, native bottom-edge resize dragging in reading and editing modes, saved heights, folding, Escape cancellation, keyboard sizing and automatic-height reset, inline creation and editing, live typed/pasted Markdown, Escape and outside-click flushing, automatic updates, immediate-close flushing, inline autosave, conflict recovery, stronger dark highlights, floating toolbar, marks, links, lists, headings, code, Markdown round-trip, native title/search undo, body typing and formatting undo and redo, sanitization, and MCP readability.');
  } catch (error) {
    console.error('Rich editor check failed:', error);
    console.log('Formatting focus:', await run(`({active:document.activeElement?.tagName, activeLabel:document.activeElement?.getAttribute('aria-label'), link:document.querySelector('.bubble-link')?.outerHTML, selection:document.querySelector('.rich-body')?.editor?.state.selection.toJSON()})`));
    throw error;
  }
  finally { if (priorClipboard.length) await clipboard.write(priorClipboard); else clipboard.clear(); }
}
