import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'node:http';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { app, screen, nativeTheme } from 'electron';
import { iconsSmoke } from './icons-smoke.mjs';
import { richSmoke } from './rich-smoke.mjs';

export async function runSmoke(win, store, panel) {
  const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
  const output = process.env.MARGIN_ARTIFACTS_DIR || path.join(root, 'artifacts'); await fs.mkdir(output, { recursive: true });
  const run = code => win.webContents.executeJavaScript(`{ ${code} }`, true).catch(e => { throw new Error(`Renderer check failed: ${code}\n${e.message}`); });
  const waitFor = async code => { for (let i = 0; i < 80; i++) { if (await run(code)) return; await new Promise(r => setTimeout(r, 100)); } throw new Error(`Timed out: ${code}`); };
  const waitNative = async check => { for (let i = 0; i < 800; i++) { if (check()) return; await new Promise(r => setTimeout(r, 10)); } throw new Error('Timed out waiting for the native panel'); };
  const click = label => run(`Array.from(document.querySelectorAll('[aria-label]')).find(el=>el.getAttribute('aria-label')===${JSON.stringify(label)}).click()`);
  const screenshot = async name => { await new Promise(r => setTimeout(r, 200)); await fs.writeFile(path.join(output, name), (await win.webContents.capturePage()).toPNG()); };
  await store.setDemoMode(true);
  await waitFor(`document.querySelectorAll('.note-card').length === 6`);
  assert.equal(win.isVisible(), false, 'Startup must leave only the edge tab visible');
  if (process.platform === 'darwin') {
    assert.equal(app.dock.isVisible(), false, 'Utility must stay out of the Dock');
    assert.equal(win.isHiddenInMissionControl(), true);
  }
  assert.equal(win.isResizable(), false);
  assert.equal(win.isMinimizable(), false);
  assert.equal(win.isMaximizable(), false);
  assert.deepEqual(win.getBounds(), win.getContentBounds(), 'No native titlebar may reserve space');
  assert.equal(await run(`Boolean(document.querySelector('.window-bar'))`), false);
  assert.equal(panel.edgeBars.size, screen.getAllDisplays().length);
  const edgeBar = panel.edgeBars.values().next().value;
  if (edgeBar.webContents.isLoading()) await new Promise(resolve => edgeBar.webContents.once('did-finish-load', resolve));
  await waitNative(() => edgeBar.isVisible());
  assert.equal(edgeBar.isVisible(), true, 'The edge tab must be discoverable at startup');
  await edgeBar.webContents.executeJavaScript(`document.querySelector('button').click()`, true);
  await waitNative(() => win.isVisible());
  assert.equal(win.isVisible(), true, 'Clicking the edge tab opens the panel');
  assert.equal(edgeBar.isVisible(), false);
  const reducedMotion = await run(`matchMedia('(prefers-reduced-motion: reduce)').matches`);
  const translation = () => run(`new DOMMatrixReadOnly(getComputedStyle(document.getElementById('root')).transform).m41`);
  if (!reducedMotion) {
    await waitFor(`document.getElementById('root').getAnimations().length === 1`);
    const start = await translation();
    assert.ok(start > 0 && start < win.getBounds().width * 1.02, 'Right-edge opening starts to the right of its resting position');
    assert.equal(win.hasShadow(), false, 'Native shadow must not pop in ahead of the moving panel');
    await new Promise(r => setTimeout(r, 45));
    assert.ok(await translation() < start, 'The complete panel travels smoothly toward its resting position');
    await fs.writeFile(path.join(output, 'margin-slide-in.png'), (await win.webContents.capturePage()).toPNG());
  }
  await waitNative(() => panel.motion.phase === 'open');
  await waitFor(`document.getElementById('root').dataset.panelMotion === 'open'`);
  assert.equal(Math.round(await translation()), 0);
  assert.equal(win.hasShadow(), true);
  assert.equal(await run(`Boolean(window.margin)`), true);
  assert.equal(await run(`typeof window.require`), 'undefined');
  await screenshot('margin-notes.png');
  await iconsSmoke({ win, store, run, waitFor, click, screenshot });
  // Exercise the renderer's drag handlers, real IPC, and persistent notebook.
  const cardIds = () => run(`Array.from(document.querySelectorAll('.note-card')).map(el => el.dataset.noteId)`);
  const tabIds = () => run(`Array.from(document.querySelectorAll('.folder-tab')).map(el => el.dataset.folderId)`);
  const dragStart = selector => run(`
    window.smokeDragSource = document.querySelector(${JSON.stringify(selector)});
    window.smokeDragTransfer = new DataTransfer();
    window.smokeDragSource.dispatchEvent(new DragEvent('dragstart', { bubbles: true, cancelable: true, dataTransfer: window.smokeDragTransfer }));
  `);
  const dragTarget = (selector, event, placement, axis) => run(`
    const target = document.querySelector(${JSON.stringify(selector)}), bounds = target.getBoundingClientRect();
    target.dispatchEvent(new DragEvent(${JSON.stringify(event)}, { bubbles: true, cancelable: true, dataTransfer: window.smokeDragTransfer,
      clientX: bounds.left + bounds.width * ${axis === 'x' ? placement === 'before' ? .25 : .75 : .5},
      clientY: bounds.top + bounds.height * ${axis === 'y' ? placement === 'before' ? .25 : .75 : .5} }));
  `);
  const dragEnd = () => run(`window.smokeDragSource.dispatchEvent(new DragEvent('dragend', { bubbles: true, dataTransfer: window.smokeDragTransfer })); delete window.smokeDragSource; delete window.smokeDragTransfer;`);
  const seedIds = await cardIds();
  await dragStart(`[data-note-id="${seedIds[1]}"]`);
  await dragTarget(`[data-note-id="${seedIds[0]}"]`, 'dragover', 'before', 'y');
  await waitFor(`document.querySelector('[data-note-id="${seedIds[0]}"]').classList.contains('drop-before')`);
  await screenshot('margin-note-drag.png');
  await dragTarget(`[data-note-id="${seedIds[0]}"]`, 'drop', 'before', 'y');
  await dragEnd();
  await waitFor(`document.querySelector('.note-card').dataset.noteId === '${seedIds[1]}'`);
  assert.equal((await store.list()).notes[0].id, seedIds[1]);
  assert.equal((await store.get(seedIds[1])).attachments.length, 0, 'Internal note drops must not attach files');
  await dragStart('[data-folder-id="work"]');
  await dragTarget('[data-folder-id="inbox"]', 'dragover', 'before', 'x');
  await waitFor(`document.querySelector('[data-folder-id="inbox"]').classList.contains('drop-before')`);
  await screenshot('margin-tab-drag.png');
  await dragTarget('[data-folder-id="inbox"]', 'drop', 'before', 'x');
  await dragEnd();
  await waitFor(`document.querySelectorAll('.folder-tab')[1].dataset.folderId === 'work'`);
  await dragStart('[data-folder-id="all"]');
  await dragTarget('[data-folder-id="personal"]', 'drop', 'after', 'x');
  await dragEnd();
  await waitFor(`document.querySelectorAll('.folder-tab')[3].dataset.folderId === 'all'`);
  assert.deepEqual(await tabIds(), ['work', 'inbox', 'personal', 'all']);
  assert.equal(await run(`document.querySelector('.folder-tab.selected').dataset.folderId`), 'all', 'Dragging tabs must keep the active folder');
  const savedRevision = (await store.read()).revision;
  await dragStart('[data-folder-id="inbox"]');
  await dragTarget('[data-folder-id="work"]', 'dragover', 'before', 'x');
  await dragEnd();
  await waitFor(`!document.querySelector('.is-dragging, .drop-before, .drop-after')`);
  assert.equal((await store.read()).revision, savedRevision, 'Canceling a drag must not save a move');
  await run(`document.querySelector('[data-folder-id="personal"]').dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, altKey: true, key: 'ArrowLeft' }));`);
  await waitFor(`document.querySelectorAll('.folder-tab')[1].dataset.folderId === 'personal'`);
  await run(`document.querySelector('[data-note-id="${seedIds[0]}"]').dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, altKey: true, key: 'ArrowUp' }));`);
  await waitFor(`document.querySelector('.note-card').dataset.noteId === '${seedIds[0]}'`);
  await run(`const card = document.querySelector('.note-card'); card.querySelector('.note-body').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));`);
  assert.equal(await run(`document.querySelector('.note-card').draggable`), false, 'Selecting note text must not initiate a reorder');
  await run(`document.querySelector('.note-card .note-type').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));`);
  assert.equal(await run(`document.querySelector('.note-card').draggable`), true);
  const savedCardIds = await cardIds(), savedTabIds = await tabIds();
  win.webContents.reload();
  await waitFor(`document.querySelectorAll('.note-card').length === 6`);
  assert.deepEqual(await cardIds(), savedCardIds, 'Note order survives a renderer reload');
  assert.deepEqual(await tabIds(), savedTabIds, 'Tab order survives a renderer reload');
  const client = new Client({ name: 'smoke-codex', version: '1' });
  const transport = new StdioClientTransport({ command: process.execPath, args: [path.join(root, 'server/index.mjs')], env: { ...process.env, ELECTRON_RUN_AS_NODE: '1', MARGIN_DATA_DIR: store.dir }, stderr: 'pipe' });
  await client.connect(transport);
  let vaultServer;
  try {
    const result = await client.callTool({ name: 'create_note', arguments: { title: 'Live from Codex', body: '- [ ] Verify live sync\n\nAdded through a real MCP connection.', kind: 'checklist', color: 'sky', source: 'Codex' } });
    assert.ok(!result.isError, result.content?.[0]?.text); const note = JSON.parse(result.content[0].text);
    await waitFor(`Boolean(document.querySelector('[data-note-id="${note.id}"]'))`);
    await run(`document.querySelector('[data-note-id="${note.id}"] .task-check').click()`);
    await waitFor(`document.querySelector('[data-note-id="${note.id}"] .task-check').classList.contains('checked')`);
    assert.match((await store.get(note.id)).body, /- \[x\] Verify/);
    await run(`document.querySelector('[data-note-id="${note.id}"] .card-title').dispatchEvent(new MouseEvent('click', {bubbles:true,detail:1}))`);
    assert.equal(await run(`Boolean(document.querySelector('.editor'))`), false, 'A single mouse click must not open the editor');
    await run(`document.querySelector('[data-note-id="${note.id}"] .task-check').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
    assert.equal(await run(`Boolean(document.querySelector('.editor'))`), false, 'Double-clicking an interactive control must not open the editor');
    await run(`document.querySelector('[data-note-id="${note.id}"] .note-body p').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
    await waitFor(`Boolean(document.querySelector('.editor-title'))`);
    await run(`const input = document.querySelector('.editor-title'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Edited in the panel'); input.dispatchEvent(new Event('input',{bubbles:true}));`);
    await click('Done editing');
    await waitFor(`!document.querySelector('.editor')`);
    assert.equal((await store.get(note.id)).title, 'Edited in the panel');
    await run(`document.querySelector('[data-note-id="${note.id}"] .card-title').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
    await waitFor(`Boolean(document.querySelector('.editor'))`);
    await click('Done editing');
    await waitFor(`!document.querySelector('.editor')`);
    await run(`document.querySelector('[data-note-id="${note.id}"]').dispatchEvent(new KeyboardEvent('keydown', {bubbles:true,key:'Enter'}))`);
    await waitFor(`Boolean(document.querySelector('.editor'))`);
    await click('Done editing');
    await waitFor(`!document.querySelector('.editor')`);

    await richSmoke({win,store,client,run,waitFor,click,screenshot});

    // Search the actual renderer, then clear it.
    await run(`const input = document.querySelector('[aria-label="Search notes"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Edited in'); input.dispatchEvent(new Event('input',{bubbles:true}));`);
    await waitFor(`document.querySelectorAll('.note-card').length === 1`);
    await click('Clear search');
    // Open the connection view and check that it uses this app's data directory.
    await run(`document.querySelector('.connect-banner').click()`);
    await waitFor(`document.querySelector('.config-box pre')?.textContent.includes('mcp add margin')`);
    assert.ok((await run(`document.querySelector('.config-box pre').textContent`)).includes(store.dir));
    await waitFor(`!document.querySelector('.toast')`);
    await screenshot('margin-connect.png');
    await click('Back to notes');
    await click('Preferences');
    await waitFor(`Boolean(document.querySelector('.preferences-content'))`);
    await click('Themes');
    await waitFor(`Boolean(document.querySelector('.themes-content'))`);
    await click('Dark appearance');
    await waitFor(`document.documentElement.dataset.theme === 'dark'`);
    await screenshot('margin-themes-dark.png');
    await click('Back to preferences');
    await click('Back to notes');
    await screenshot('margin-dark.png');
    await click('Preferences'); await click('Themes');
    await click('System appearance');
    await waitFor(`document.querySelector('[aria-label="System appearance"]').getAttribute('aria-pressed') === 'true'`);
    assert.equal(nativeTheme.themeSource, 'system');
    assert.equal(await run(`document.documentElement.dataset.theme`), nativeTheme.shouldUseDarkColors ? 'dark' : 'light');
    nativeTheme.themeSource = 'dark';
    await waitFor(`document.documentElement.dataset.theme === 'dark'`);
    nativeTheme.themeSource = 'light';
    await waitFor(`document.documentElement.dataset.theme === 'light'`);
    nativeTheme.themeSource = 'system';
    await click('Light appearance');
    await waitFor(`document.documentElement.dataset.theme === 'light'`);
    await screenshot('margin-themes.png');
    await click('Use CXTasks Glass theme');
    await click('Dark appearance');
    await waitFor(`document.documentElement.dataset.material === 'glass' && document.documentElement.dataset.theme === 'dark'`);
    assert.notEqual(await run(`getComputedStyle(document.querySelector('[data-folder-id="all"] svg')).color`), await run(`getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()`));
    assert.equal(await run(`getComputedStyle(document.querySelector('.heading-glyph')).display`), 'block');
    assert.equal(await run(`document.querySelectorAll('.folders .folder-dot').length`), 0, 'Folder tabs use the selectable icon instead of a color dot');
    const systemPrefs = await run(`window.margin.appearancePreferences()`);
    if (process.platform === 'darwin' && !systemPrefs.reducedTransparency) {
      assert.equal(panel.material.status.backend, 'desktop-blur', 'The bridge must apply the same desktop blur as CXTasks on this Mac');
      assert.ok(panel.material.status.radius > 0);
    }
    await screenshot('margin-glass-themes-dark.png');
    await click('Back to preferences'); await click('Back to notes');
    await screenshot('margin-glass-dark.png');
    await run(`Array.from(document.querySelectorAll('.folders > button')).find(el=>el.textContent==='Work').click()`);
    await waitFor(`document.querySelector('.section-heading h2').textContent === 'Work'`);
    assert.equal(await run(`getComputedStyle(document.querySelector('.heading-glyph')).color`), await run(`getComputedStyle(document.querySelector('[data-folder-id="work"] .folder-glyph')).color`), 'Folder and heading hues must match');
    await run(`Array.from(document.querySelectorAll('.folders > button')).find(el=>el.textContent==='All').click()`);
    await click('Preferences'); await click('Themes');
    await run(`const input = document.querySelector('[aria-label="Glass transparency"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'0.65'); input.dispatchEvent(new Event('input',{bubbles:true}));`);
    // Closing settings immediately after a drag must still save its last value.
    await click('Back to preferences');
    await waitNative(() => panel.material.status.radius === 35 || systemPrefs.reducedTransparency);
    assert.equal((await store.read()).settings.glassTransparency, .65);
    await click('Themes');
    await run(`window.margin.settings({glassTransparency:0})`);
    await waitFor(`document.documentElement.style.getPropertyValue('--glass-pane-alpha') === '1'`);
    assert.equal(panel.material.status.backend, 'none', 'Opaque means no native blur');
    await run(`window.margin.settings({glassTransparency:.38})`);
    const originalNativeTheme = panel.material.nativeTheme;
    panel.material.nativeTheme = { shouldUseDarkColors: true, prefersReducedTransparency: true };
    panel.material.render(true);
    win.webContents.send('appearance:preferences', { reducedTransparency: true });
    await waitFor(`document.querySelector('[aria-label="Glass transparency"]').disabled`);
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--glass-sidebar-alpha')`), '1');
    assert.equal(panel.material.status.backend, 'none');
    assert.equal((await store.read()).settings.glassTransparency, .38);
    panel.material.nativeTheme = originalNativeTheme; panel.material.render(true);
    win.webContents.send('appearance:preferences', systemPrefs);
    await click('Light appearance');
    await waitFor(`document.documentElement.dataset.theme === 'light'`);
    await screenshot('margin-glass-themes-light.png');
    await click('Back to preferences'); await click('Back to notes');
    await screenshot('margin-glass-light.png');
    const desktopGlass = process.platform === 'darwin' && !systemPrefs.reducedTransparency;
    const glassRadius = panel.material.status.radius;
    panel.hide();
    if (desktopGlass) {
      assert.equal(panel.material.status.backend, 'desktop-blur', 'Glass must remain active while dismissal is prepared');
      await waitNative(() => panel.motion.phase === 'closing' || panel.motion.phase === 'closed');
      if (panel.motion.phase === 'closing') assert.equal(panel.material.status.radius, glassRadius, 'The closing slide must keep the settled blur');
    }
    await waitNative(() => panel.motion.phase === 'closed');
    assert.equal(panel.material.status.backend, 'none', 'Native blur is suspended while the panel is hidden');
    panel.show();
    await waitNative(() => panel.motion.phase === 'opening' || panel.motion.phase === 'open');
    if (desktopGlass) assert.equal(panel.material.status.radius, glassRadius, 'Glass must be active before the opening animation starts');
    await waitNative(() => panel.motion.phase === 'open');
    if (desktopGlass) assert.equal(panel.material.status.backend, 'desktop-blur');
    await click('Preferences'); await click('Themes');
    await click('Use Default theme');
    await waitFor(`document.documentElement.dataset.material === 'default'`);
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--hue-teal')`), '');
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--glass-pane-alpha')`), '');
    assert.ok(await run(`document.querySelector('.heading-glyph').getBoundingClientRect().width > 0`), 'Section icons remain visible in Default so chosen icons can be used in every theme');
    // Serve the same protocol as Onyx so light/dark changes and disconnections
    // are deterministic without changing the person's actual Obsidian theme.
    let vaultMode = 'light', available = true;
    const lightColors = { 'bg-primary': '253 246 227', 'bg-sidebar': '253 246 227', 'bg-surface': '241 234 210', 'bg-elevated': '253 246 227', 'bg-input': '244 237 214', ink: '0 43 54', secondary: '68 98 101', muted: '121 140 137', faint: '164 175 166', accent: '203 75 22', 'accent-hover': '152 67 30' };
    const darkColors = { ...lightColors, 'bg-primary': '0 43 54', 'bg-sidebar': '0 43 54', 'bg-surface': '7 50 60', 'bg-elevated': '14 57 65', 'bg-input': '18 58 66', ink: '253 246 227', secondary: '198 195 181', muted: '166 170 161', faint: '121 140 137', accent: '240 173 88', 'accent-hover': '215 150 75' };
    vaultServer = createServer((_request, response) => {
      if (!available) { response.writeHead(302, { Location: 'https://example.com' }); response.end(); return; }
      if (_request.url === '/api/markdown-theme') {
        const tones = vaultMode === 'light' ? [[163,51,97],[139,94,17],[43,116,49],[18,116,111],[101,76,178],[132,68,160]] : [[240,120,160],[230,195,125],[130,235,130],[114,224,214],[154,141,247],[197,146,222]];
        const css = `body[data-askw-document-kind="markdown"]{color-scheme:${vaultMode}}` + tones.map((c,i) => `body[data-askw-document-kind="markdown"] > main h${i+1}{color:rgb(${c.join(', ')})}`).join('') + 'body[data-askw-document-kind="markdown"] > main a{color:rgb(88, 209, 235)}';
        response.setHeader('Content-Type', 'application/json'); response.end(JSON.stringify({ok:true,available:true,enabled:true,css})); return;
      }
      if (_request.url === '/api/sidebar-theme') {
        const folders = vaultMode === 'dark' ? [{name:'Inbox',color:'rgb(230, 195, 125)'},{name:'Work',color:'rgb(130, 235, 130)'}] : [{name:'Inbox',color:'rgb(139, 94, 17)'},{name:'Work',color:'rgb(43, 116, 49)'}];
        response.setHeader('Content-Type', 'application/json'); response.end(JSON.stringify({ok:true,available:true,enabled:true,css:`body.obsidian-tree aside{color-scheme:${vaultMode}}`,folders})); return;
      }
      const colors = vaultMode === 'light' ? lightColors : darkColors;
      const css = ':root.vault-look{' + Object.entries(colors).map(([k, v]) => `--${k}:${v}`).join(';') + ';--ui-font:"JetBrains Mono", Inter}';
      response.setHeader('Content-Type', 'application/json'); response.end(JSON.stringify({ ok: true, available: true, mode: vaultMode, css, revision: vaultMode === 'light' ? 'abcdef' : '123456' }));
    });
    await new Promise(resolve => vaultServer.listen(0, '127.0.0.1', resolve));
    const address = `http://127.0.0.1:${vaultServer.address().port}`;
    assert.equal((await run(`window.margin.settings({vaultAddress:${JSON.stringify(address)}})`)).ok, true);
    await run(`window.margin.vaultTheme(true)`);
    await waitFor(`!document.querySelector('[aria-label="Save vault theme copy"]').disabled`);
    await click('Match vault');
    await waitFor(`document.documentElement.style.getPropertyValue('--bg') === 'rgb(253 246 227)'`);
    assert.equal(await run(`getComputedStyle(document.documentElement).fontFamily.includes('JetBrains Mono')`), true);
    assert.equal(await run(`document.querySelector('[aria-label="Dark appearance"]').disabled`), true);
    await screenshot('margin-vault-theme.png');
    assert.equal(await run(`document.documentElement.dataset.material`), 'vault');
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--heading-1')`), 'rgb(163 51 97)');
    await click('Back to preferences'); await click('Back to notes');
    const colourNoteResult = await client.callTool({name:'create_note',arguments:{title:'A quieter vault palette',body:'# A little colour\n\nOrdinary text stays neutral.\n\n## Plans and next steps\n\n### Things worth keeping\n\n#### A little context\n\n##### Details\n\n###### References\n\n[One useful link](https://example.com)',pinned:true}});
    const colourNote=JSON.parse(colourNoteResult.content[0].text);
    await waitFor(`Boolean(document.querySelector('[data-note-id="${colourNote.id}"] .markdown h6'))`);
    assert.equal(await run(`getComputedStyle(document.querySelector('[data-note-id="${colourNote.id}"] .card-title')).color`), await run(`getComputedStyle(document.querySelector('.main-header .brand')).color`), 'Card titles remain neutral');
    assert.notEqual(await run(`getComputedStyle(document.querySelector('[data-note-id="${colourNote.id}"] .markdown h1')).color`), await run(`getComputedStyle(document.querySelector('[data-note-id="${colourNote.id}"] .markdown')).color`), 'Markdown headings retain a softened hint of colour');
    await run(`document.querySelector('[data-note-id="${colourNote.id}"]').scrollIntoView({block:'start'})`);
    await screenshot('margin-vault-colours-light.png');
    await click('Preferences'); await click('Themes');

    await click('Save vault theme copy');
    await waitFor(`Boolean(document.querySelector('[aria-label="Theme name"]'))`);
    await run(`const input = document.querySelector('[aria-label="Theme name"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'My vault copy'); input.dispatchEvent(new Event('input',{bubbles:true}));`);
    await run(`document.querySelector('.theme-copy-form button[type="submit"]').click()`);
    await waitFor(`Boolean(document.querySelector('[aria-label="Use My vault copy theme"]'))`);
    const savedThemeId = (await store.read()).settings.themeId;
    assert.equal((await store.read()).themes[0].name, 'My vault copy');
    vaultMode = 'dark';
    await run(`window.margin.vaultTheme(true)`);
    assert.equal(await run(`document.documentElement.dataset.theme`), 'light', 'A saved copy must keep its captured look');
    await click('Match vault');
    await waitFor(`document.documentElement.dataset.theme === 'dark'`);
    assert.equal(nativeTheme.themeSource, 'dark');
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--heading-1')`), 'rgb(240 120 160)');
    await click('Back to preferences'); await click('Back to notes');
    await run(`document.querySelector('[data-note-id="${colourNote.id}"]').scrollIntoView({block:'start'})`);
    await screenshot('margin-vault-colours-dark.png');
    await run(`document.querySelector('[data-note-id="${colourNote.id}"] .card-title').dispatchEvent(new MouseEvent('dblclick', {bubbles:true,detail:2}))`);
    await waitFor(`Boolean(document.querySelector('.editor'))`);
    await screenshot('margin-vault-editor-dark.png');
    await click('Done editing');
    await waitFor(`!document.querySelector('.editor')`);
    await click('Preferences'); await click('Themes');
    available = false;
    const offline = await run(`window.margin.vaultTheme(true)`);
    assert.equal(offline.value.connected, false, 'Redirects must never escape loopback');
    assert.equal(await run(`document.documentElement.dataset.theme`), 'dark', 'Offline use retains the cached vault appearance');
    available = true;
    await click('Use My vault copy theme');
    await waitFor(`Boolean(document.querySelector('.saved-theme-actions'))`);
    await run(`Array.from(document.querySelectorAll('.saved-theme-actions button')).find(el=>el.textContent.includes('Update from vault')).click()`);
    await waitFor(`document.querySelector('[aria-label="Use My vault copy theme"] small').textContent.includes('Light + Dark')`);
    await click('Light appearance');
    await waitFor(`document.documentElement.dataset.theme === 'light'`);
    assert.equal((await store.read()).settings.themeId, savedThemeId);
    assert.equal(await run(`document.documentElement.dataset.material`), 'vault');
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--heading-1')`), 'rgb(163 51 97)');
    await click('Use Default theme');
    await waitFor(`document.documentElement.style.getPropertyValue('--bg') === '#f6f5f1'`);
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--button-ink')`), '', 'No copied palette token may linger in Default');
    assert.equal(await run(`document.documentElement.style.getPropertyValue('--heading-1')`), '', 'No vault heading colour may linger in Default');
    // The removal control is visible only for the selected saved copy.
    await click('Use My vault copy theme');
    await waitFor(`Boolean(document.querySelector('[aria-label="Remove My vault copy theme"]'))`);
    await click('Remove My vault copy theme');
    await waitFor(`!document.querySelector('[aria-label="Use My vault copy theme"]')`);
    assert.equal((await store.read()).settings.themeId, 'default');
    await click('Back to preferences'); await click('Back to notes');
    const errors = await run(`Array.from(document.querySelectorAll('img')).filter(img=>!img.complete || img.naturalWidth===0).map(img=>img.src)`); assert.deepEqual(errors, []);
    await click('Hide Margin');
    if (!reducedMotion) assert.equal(win.isVisible(), true, 'The window stays visible until its slide out finishes');
    await waitNative(() => panel.motion.phase === 'closed');
    assert.equal(win.isVisible(), false);
    assert.equal(edgeBar.isVisible(), true, 'Hiding the panel restores its edge tab');
    panel.show(); await waitNative(() => panel.motion.phase === 'open');
    await click('Preferences'); await click('Show screen-edge tab');
    await waitFor(`!document.querySelector('[aria-label="Show screen-edge tab"]').checked`);
    assert.equal((await store.read()).settings.showEdgeTab, false);
    await screenshot('margin-edge-tab-setting.png');
    await click('Back to notes');
    panel.hide(); await waitNative(() => panel.motion.phase === 'closed');
    assert.equal([...panel.edgeBars.values()].some(bar=>bar.isVisible()), false, 'Disabling the tab must keep every display clear');
    panel.toggle(); await waitNative(() => panel.motion.phase === 'open');
    assert.equal(win.isVisible(), true, 'Shortcut/menu callback opens the panel without an edge tab');
    win.webContents.reload(); await waitFor(`Boolean(document.querySelector('.note-card'))`);
    await click('Preferences');
    assert.equal(await run(`document.querySelector('[aria-label="Show screen-edge tab"]').checked`), false, 'The tab preference survives reloads');
    await click('Show screen-edge tab'); await click('Back to notes');
    panel.hide(); await waitNative(() => panel.motion.phase === 'closed');
    await waitNative(() => edgeBar.isVisible());
    const resultSettings = await run(`window.margin.settings({edge:'left'})`);
    assert.equal(resultSettings.ok, true);
    assert.equal(edgeBar.getBounds().x, screen.getAllDisplays()[0].bounds.x);
    // The same toggle callback serves ⌘ ⇧ Space and the menu bar.
    panel.toggle();
    await waitNative(() => panel.motion.phase === 'opening' || panel.motion.phase === 'open');
    const restingBounds = win.getBounds();
    if (!reducedMotion) {
      assert.ok(await translation() < 0, 'The left edge reverses the opening direction');
      assert.deepEqual(win.getBounds(), restingBounds, 'Animation stays clipped to this monitor instead of moving onto an adjacent one');
      await new Promise(r => setTimeout(r, 60));
      panel.toggle();
      await waitNative(() => panel.motion.phase === 'closing');
      const beforeReverse = await translation();
      panel.toggle();
      await waitNative(() => panel.motion.phase === 'opening');
      const resumedFrom = await run(`new DOMMatrixReadOnly(document.getElementById('root').getAnimations()[0]?.effect.getKeyframes()[0].transform || document.getElementById('root').style.transform).m41`);
      assert.ok(Math.abs(resumedFrom - beforeReverse) < 45, `Rapid shortcut presses must reverse from the current position (${beforeReverse} → ${resumedFrom})`);
    }
    await waitNative(() => panel.motion.phase === 'open');
    assert.deepEqual(win.getBounds(), restingBounds, 'The native window remains anchored throughout the slide');
    panel.hide(); await waitNative(() => panel.motion.phase === 'closed');
    const originalReduction = panel.motion.reducedMotion;
    panel.motion.reducedMotion = () => true;
    panel.show(); await waitNative(() => panel.motion.phase === 'open');
    assert.equal(Math.round(await translation()), 0);
    assert.equal(await run(`document.getElementById('root').getAnimations().length`), 0, 'Reduce Motion bypasses the slide');
    panel.hide(); await waitNative(() => panel.motion.phase === 'closed');
    panel.motion.reducedMotion = originalReduction;
    await run(`window.margin.settings({edge:'right'})`);
    panel.show(); await waitNative(() => panel.motion.phase === 'open');
    await click('Leave demo notebook');
    await waitFor(`!document.querySelector('.demo-badge') && document.querySelectorAll('.note-card').length === 0`);
    assert.equal((await store.read()).demo, null);
    // Preferences must switch notebooks without carrying drafts, filters or search.
    const regularResult = await client.callTool({ name: 'create_note', arguments: { title: 'Regular notebook', body: 'Keep me after a demo.', source: 'Codex' } });
    const regularNote = JSON.parse(regularResult.content[0].text);
    await waitFor(`Boolean(document.querySelector('[data-note-id="${regularNote.id}"]'))`);
    const regularId = (await store.read()).notebookId;
    const regularDraftKey = 'margin-note-draft:' + regularId;
    await run(`localStorage.setItem(${JSON.stringify(regularDraftKey)},JSON.stringify({title:'Regular draft',body:'Keep this draft',folderId:'inbox',color:'paper',kind:'note',pinned:false}))`);
    await click('Preferences');
    await run(`document.querySelector('[aria-label="Start demo mode"]').scrollIntoView({block:'center'})`);
    await screenshot('margin-demo-preferences.png');
    await click('Start demo mode');
    await waitFor(`Boolean(document.querySelector('.demo-badge')) && document.querySelectorAll('.note-card').length === 6`);
    assert.equal(await run(`Boolean(document.querySelector('.draft-notice'))`), false, 'Regular drafts must stay out of the demo');
    await screenshot('margin-demo-mode.png');
    const demoInputResult = await client.callTool({ name: 'create_note', arguments: { title: 'Temporary demo input', source: 'Codex' } });
    const demoInput = JSON.parse(demoInputResult.content[0].text);
    await waitFor(`Boolean(document.querySelector('[data-note-id="${demoInput.id}"]'))`);
    await click('Preferences');
    assert.equal(await run(`document.querySelector('[aria-label="Reset to default"]').disabled`), true, 'Reset must be unavailable while demo mode is active');
    await click('Exit demo mode');
    await waitFor(`!document.querySelector('.demo-badge') && Boolean(document.querySelector('[data-note-id="${regularNote.id}"]'))`);
    assert.equal(await run(`Boolean(document.querySelector('[data-note-id="${demoInput.id}"]'))`), false);
    assert.equal(await run(`Boolean(document.querySelector('.draft-notice'))`), true, 'Leaving demo mode restores the regular draft');
    await click('Preferences');
    await click('Reset to default');
    await waitFor(`Boolean(document.querySelector('[aria-label="Reset notebook confirmation"]'))`);
    await run(`Array.from(document.querySelectorAll('[role="alertdialog"] button')).find(el=>el.textContent==='Cancel').click()`);
    assert.equal((await store.read()).notes.length, 1, 'Cancel must keep all existing notes');
    await click('Reset to default');
    await screenshot('margin-reset-confirmation.png');
    await click('Confirm reset notebook');
    await waitFor(`!document.querySelector('.overlay') && document.querySelectorAll('.note-card').length === 0`);
    assert.equal(await run(`Boolean(document.querySelector('.draft-notice'))`), false, 'Reset must not recover an old draft into the blank notebook');
    assert.equal((await store.read()).demo, null);
    assert.equal((await store.read()).activity.length, 0);
    await screenshot('margin-empty-notebook.png');
    // Leave a pending edit for the real app.quit() lifecycle to flush. The smoke
    // runner checks the persisted notebook after the process exits.
    await click('New note');
    await waitFor(`Boolean(document.querySelector('.rich-body')?.editor)`);
    await run(`const input=document.querySelector('.editor-title'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Quit autosave check'); input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('.rich-body').editor.commands.insertContent('Keep the final keystrokes on quit');`);
    console.log('Electron smoke passed: note and tab drag reordering, insertion indicators, cancellation, keyboard moves, persisted order, native edge panel, smooth slide in/out on both edges, shortcut reversals, monitor clipping, Reduce Motion, real MCP live sync, editing, search, themes and vault copies, isolated demo mode, draft restoration and empty reset.');
  } finally { await client.close(); if (vaultServer) await new Promise(resolve => vaultServer.close(resolve)); }
}
